name: Build and Publish Images to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mamba-docker
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u mattmajestic --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as the build context
          tags: mattmajestic/wsop-cashes:latest
          push: true
