name: Build and Publish Images to DockerHub

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wsop-cashes
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u mattmajestic --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as the build context
          tags: mattmajestic/wsop-cashes:latest
          push: true
          
      - name: Build and Push Docker Image for Streamlit
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.streamlit  # Use the Dockerfile.streamlit for this step
          tags: mattmajestic/wsop-cashes-streamlit:latest
          push: true